version: 2
sources:
  - name: raw
    tables:
      - name: customers
        description: Raw table that gives customer information
      - name: order_items
        description: Raw table that gives item level details for an order
      - name: orders
        description: Raw table that gives order level details
      - name: payments
        description: Raw table that gives payment details for an order
      - name: products
        description: Raw table that gives products information
  - name: dbt_sandbox1
    tables:
      - name: dim_date
        description: Date dimension
models:
  - name: fact_sales
    description: Provides the total delivery time (in days) for an order item and if the customer has placed a repeat order.
    columns:
      - name: order_item_id
        description: Order item id
        tests:
          - not_null
      - name: total_delivery_time
        description: The duration between purchase date and order delivery date
      - name: new_repeat_purchase
        description: Indicates if it's the first purchase for a customer or it's a repeat purchase
        tests:
          - accepted_values:
              values: ['New Purchase', 'Repeat Purchase']
  - name: dim_customers
    description: Gives an insight into customers purchase patterns
    columns:
      - name: customer_unique_id
        description: Unique id for a customer
        tests:
          - unique
          - not_null
      - name: date_of_first_order
        description: Date of the first order placed by customer
      - name: date_of_most_recent_order
        description: Date of the most recent order placed by customer
      - name: number_of_orders
        description: Number of orders placed by customer so far
      - name: total_order_value
        description: Total amount of all the orders placed by the customer
      - name: value_of_most_expensive_order
        description: Price of the most expensive order placed by the customer
  - name: dim_products
    description: Shows the total revenue and units sold for a product along with the product ranking of 'Top 10' or 'Not Top 10'
    columns:
      - name: product_id
        description: Unique id for product
        tests:
          - unique
          - not_null
      - name: product_volume
        description: The total volume of the product in cubic cms
      - name: total_units_sold
        description: Total units sold for the product
      - name: total_revenue
        description: Total revenue generated by the product
      - name: is_top_10
        description: Indicates if it's one of the top 10 products based on the number of units sold
        tests:
          - accepted_values:
              values: ['Top 10', 'Not Top 10']
  - name: fact_daily_products_sold
    description: Gives daily snapshot of total units sold for a product
    columns:
      - name: date
        description: Date of sale
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_day
      - name: product_id
        description: product_id sold
      - name: total_units_sold
        description: Total units sold for the product on a given day
  - name: dim_date
    description: Date dimension
    columns:
      - name: date_day
        description: date
        tests:
          - unique
          - not_null
